stages:
    - build
    - test

build:
    script:
        - mkdir build
        - cd build
        - cmake ../
        - make
    stage: build
    artifacts:
        paths:
            - build/src/RapidSim.exe

run-B2Kee:
    script:
        - cd build
        - src/RapidSim.exe ../validation/B2Kee 100000
        - root -b -q -l "../validation/compareHistograms.C(\"B2Kee\")"
    stage: test
    artifacts:
        paths:
            - validation/B2Kee_hists.root

run-B2Kee-tree:
    script:
        - cd build
        - src/RapidSim.exe ../validation/B2Kee 1000 1
    stage: test
    artifacts:
        paths:
            - validation/B2Kee_tree.root

run-Bs2Jpsiphi:
    script:
        - cd build
        - src/RapidSim.exe ../validation/Bs2Jpsiphi 100000
        - root -b -q -l "../validation/compareHistograms.C(\"Bs2Jpsiphi\")"
    stage: test
    artifacts:
        paths:
            - validation/Bs2Jpsiphi_hists.root

run-Bd2D0rho0:
    script:
        - cd build
        - src/RapidSim.exe ../validation/Bd2D0rho0 100000
        - root -b -q -l "../validation/compareHistograms.C(\"Bd2D0rho0\")"
    stage: test
    artifacts:
        paths:
            - validation/Bd2D0rho0_hists.root

run-Bs2D0Kpi:
    script:
        - cd build
        - src/RapidSim.exe ../validation/Bs2D0Kpi 10000
        - root -b -q -l "../validation/compareHistograms.C(\"Bs2D0Kpi\")"
    stage: test
    artifacts:
        paths:
            - validation/Bs2D0Kpi_hists.root
