stages:
    - build
    - test

build:
    script:
        - export ROOTSYS=/usr/local/
        - mkdir build
        - cd build
        - cmake ../
        - make
    stage: build
    artifacts:
        paths:
            - build/src/RapidSim.exe

build-evtgen:
    script:
        - export ROOTSYS=/usr/local/
        - export EVTGEN_ROOT=~/evtgen/EvtGen/evtgen/
        - mkdir build-evtgen
        - cd build-evtgen
        - cmake ../
        - make
    stage: build
    artifacts:
        paths:
                - build-evtgen/src/RapidSim.exe

run-B2Kee:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/B2Kee 100000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"B2Kee\")"
    stage: test
    artifacts:
        paths:
            - build/B2Kee_hists.root

run-B2Kee-tree:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/B2Kee 1000 1
    stage: test
    artifacts:
        paths:
            - build/B2Kee_tree.root

run-Bs2Jpsiphi:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/Bs2Jpsiphi 100000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"Bs2Jpsiphi\")"
    stage: test
    artifacts:
        paths:
            - build/Bs2Jpsiphi_hists.root

run-Bd2D0rho0:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/Bd2D0rho0 100000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"Bd2D0rho0\")"
    stage: test
    artifacts:
        paths:
            - build/Bd2D0rho0_hists.root

run-Bs2D0Kpi:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/Bs2D0Kpi 10000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"Bs2D0Kpi\")"
    stage: test
    artifacts:
        paths:
            - build/Bs2D0Kpi_hists.root

run-D02Kpi:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/D02Kpi 100000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"D02Kpi\")"
    stage: test
    artifacts:
        paths:
            - build/D02Kpi_hists.root

run-B2DplusD0:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - cd build
        - src/RapidSim.exe ../validation/B2DplusD0 10000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"B2DplusD0\")"
    stage: test
    artifacts:
        paths:
            - build/B2DplusD0_hists.root

run-Ds2KKpi:
    script:
        - export RAPIDSIM_ROOT=$PWD
        - export EVTGEN_ROOT=~/evtgen/EvtGen/evtgen/
        - cd build-evtgen
        - src/RapidSim.exe ../validation/Ds2KKpi 10000
        - mkdir plots
        - root -b -q -l "../validation/compareHistograms.C(\"Ds2KKpi\")"
    stage: test
    artifacts:
        paths:
                - build-evtgen/Ds2KKpi_hists.root

